"""defines application routes and returns jsonified data to web page
generated by instantiating a GrandPyBot object based on the user input"""


from flask import Flask, render_template, request, jsonify

from app.grandpy_bot import GrandPyBot


APP = Flask(__name__)  # creates an instance of Flask class for the app


@APP.route('/')
def page():
    """returns the html file"""
    return render_template('page.html')


@APP.route('/answer')
def generate_answer():
    """returns the answer constructed when there's a user input"""
    bot = GrandPyBot(request.args.get('question'))
    return jsonify(bot.return_data())


if __name__ == "__main__":
    APP.run()
