"""empty message

Revision ID: 5741964ff375
Revises: 86c9c2547c2a
Create Date: 2019-12-22 18:16:21.258125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5741964ff375'
down_revision = '86c9c2547c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request', sa.String(length=200), nullable=False),
    sa.Column('null_api', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logging')
    # ### end Alembic commands ###
